name: Jobs
description: Job plugin for bukkit
main: com.zford.jobs.Jobs
version: 2.4.6
author: phrstbrn
softdepend: [Permissions, iConomy, BOSEconomy, Essentials, Stats]
commands:
    Jobs:
        description: Jobs
        usage: /jobs